##Abdull-Basid Mahdi
##Kimmo Koops
##Vitalii Bashilov
library(MASS)
library(tidyverse)
library(caret)
library(e1071)
data<-read.csv("/Users/vitalybashilov/Desktop/Data Mining/assignment 2/gcm_data.csv")
data_notarget<-read.csv("/Users/vitalybashilov/Desktop/Data Mining/assignment 2/gcm_notarget.csv")
#we use n=80% of the sample data for training
n=0.8
train = sample(1:nrow(data), n*nrow(data))
train.df = data[train,]
validate.df = data[-train,]
logit=glm(Serious ~ ., data = train.df, family = "binomial")
options(scipen = 999)
summary(logit)
#predicting with the first model
logit.pred = predict(logit, validate.df, type = "response")  
confusionMatrix(as.factor(ifelse(logit.pred>0.5, 1, 0)),
                as.factor(validate.df$Serious))


#logit step
logit.null=glm(Serious ~ 1, data = train.df,family = "binomial")
logit.step = step(logit.null,scope=list(lower=logit.null, upper=logit),direction = "forward")
summary(logit.step)
#predicting with the logit.step model
logit.step.pred = predict(logit.step, validate.df, type = "response")  
confusionMatrix(as.factor(ifelse(logit.step.pred>0.5, 1, 0)),
                as.factor(validate.df$Serious))
#predicting with no target data
data_notarget$Serious=predict(logit.step,data_notarget,type = "response")
data_notarget$Serious=ifelse(data_notarget$Serious>0.5, 1, 0)
#writing csv
write_csv(data_notarget,"/Users/vitalybashilov/Desktop/Data Mining/assignment 2/gcm_notarget_modified.csv")






